openapi: 3.0.0
info:
  title: HipocampusB
  description: Hipocampus backend
  version: 0.0.1
servers:
  - url: 'http://clayrite.ddns.net:42300'
    description: Development server
components:
  schemas:
    user:
      type: object
      required: [ email, password, fullname ]
      properties:
        email:
          type: string
        password:
          type: string
        fullname:
          type: string
    reservation:
      type: object
      required: [ date, paid, client, reservedBy ]
      properties:
        date:
          type: string
          example: 20-07-2023
        paid:
          type: boolean
        client:
          type: string
        reservedBy:
          type: string
paths:
  /user:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          description: The user was registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        400:
          description: The request is wrong or malformed and cannot be performed
        406:
          description: The request is unacceptable due to missing or invalid values
        409:
          description: This email is already registered on another user
  /reservation:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reservation'
      responses:
        201:
          description: The reservation was created
        409:
          description: The date is already reserved
    get:
      responses:
        200:
          description: All the reservations were retrieved

